"""UpdateDb

Revision ID: c8e1df6dd407
Revises: 106c977f50a1
Create Date: 2025-12-05 00:56:23.159318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e1df6dd407'
down_revision: Union[str, Sequence[str], None] = '106c977f50a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=256), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
